
apiVersion: v1
kind: Service
metadata:
  name: "expense-tracker-frontend"
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: "expense-tracker-frontend"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "expense-tracker-frontend"
  namespace: "default"
  labels:
    app: "expense-tracker-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "expense-tracker-frontend"
  template:
    metadata:
      labels:
        app: "expense-tracker-frontend"
    spec:
      containers:
        - name: "frontend"
          image: "registry.cloud.okteto.net/expense-tracker-kirill5k/expense-tracker-frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.05"
            limits:
              memory: "128Mi"
              cpu: "0.1"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5