version: '3'
services:

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
      MONGODB_DATABASE: expense-tracker

#  expense-tracker-core:
#    image: expense-tracker-core:latest
#    depends_on:
#      - mongodb
#    environment:
#      PORT: 8080
#      MONGO_HOST: mongodb
#      MONGO_USER: dbuser
#      MONGO_PASSWORD: dbpassword

  expense-tracker-frontend:
    build: ./modules/frontend/
    environment:
      EXPENSE_TRACKER_CORE_URL: http://expense-tracker-core:8080
    ports:
      - "3000:80"