version: "3.8"

networks:
  app-tier:
    driver: bridge

services:

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
      MONGODB_DATABASE: expense-tracker
      MONGODB_PORT_NUMBER: "27017"
    ports:
      - "27017:27017"
    networks:
      - app-tier

  expense-tracker-core:
    image: expense-tracker-core:latest
    depends_on:
      - mongodb
    environment:
      PORT: 8080
      MONGO_CONNECTION_URI: mongodb://dbuser:dbpassword@mongodb:27017/expense-tracker
    networks:
      - app-tier

  expense-tracker-frontend:
    build: ./modules/frontend/
    depends_on:
      - expense-tracker-core
    environment:
      EXPENSE_TRACKER_CORE_URL: http://expense-tracker-core:8080
    ports:
      - "8000:80"
    networks:
      - app-tier