version: "3.8"

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
      MONGO_INITDB_DATABASE: expense-tracker
    ports:
      - "27017:27017"

  expense-tracker-core:
    image: expense-tracker-core:latest
    depends_on:
      - mongodb
    environment:
      PORT: 8080
      MONGO_CONNECTION_URI: mongodb://dbuser:dbpassword@mongodb:27017

  expense-tracker-frontend:
    build: ./modules/frontend/
    depends_on:
      - expense-tracker-core
    environment:
      EXPENSE_TRACKER_CORE_URL: http://expense-tracker-core:8080
    ports:
      - "8000:80"
