apiVersion: v1
kind: Service
metadata:
  name: "web"
spec:
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: "expense-tracker-frontend"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "expense-tracker-frontend"
  labels:
    app: "expense-tracker-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "expense-tracker-frontend"
  template:
    metadata:
      labels:
        app: "expense-tracker-frontend"
    spec:
      containers:
        - name: "frontend"
          image: "kirill1/expense-tracker-frontend:latest"
          imagePullPolicy: Always
          env:
            - name: EXPENSE_TRACKER_CORE_URL
              value: "http://expense-tracker-core:8080"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi"
              cpu: "0.05"
            limits:
              memory: "32Mi"
              cpu: "0.1"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 60