addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.lightbend.sbt"         % "sbt-javaagent"       % "0.1.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.6.4")
addSbtPlugin("com.github.sbt"            % "sbt-github-actions"  % "0.18.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.11.1")
