import {
  mdiBankTransfer,
  mdiBankTransferIn,
  mdiBankTransferOut,
  mdiAccountCash,
  mdiChartAreaspline,
  mdiFinance,
  mdiPiggyBank,
  mdiSafe,
  mdiSend,
  mdiCurrencyEur,
  mdiCurrencyUsd,
  mdiBitcoin,
  mdiCamera,
  mdiGuitarAcoustic,
  mdiHeadphones,
  mdiMicrophone,
  mdiMonitor,
  mdiMusic,
  mdiPiano,
  mdiTablet,
  mdiTelevision,
  mdiController,
  mdiWatch,
  mdiDramaMasks,
  mdiBeer,
  mdiBottleSoda,
  mdiBowlMix,
  mdiCookie,
  mdiCup,
  mdiCupcake,
  mdiFish,
  mdiFoodForkDrink,
  mdiGlassCocktail,
  mdiGrill,
  mdiSilverware,
  mdiHamburger,
  mdiPizza,
  mdiBedDouble,
  mdiCake,
  mdiCoffin,
  mdiFirework,
  mdiFoodTurkey,
  mdiHalloween,
  mdiPartyPopper,
  mdiPineTree,
  mdiSnowflake,
  mdiAntenna,
  mdiWater,
  mdiFlash,
  mdiFire,
  mdiUmbrella,
  mdiWaterPump,
  mdiWeb,
  mdiWifi,
  mdiBabyCarriage,
  mdiShieldCar,
  mdiGarage,
  mdiCog,
  mdiWrench,
  mdiHammer,
  mdiGauge,
  mdiHanger,
  mdiCashRegister,
  mdiStore,
  mdiWalletGiftcard,
  mdiPill,
  mdiBasketball,
  mdiBike,
  mdiBowling,
  mdiRun,
  mdiSoccer,
  mdiTennis,
  mdiTrophy,
  mdiYoga,
  mdiTicket,
  mdiAmbulance,
  mdiBagCarryOn,
  mdiBagSuitcase,
  mdiBus,
  mdiRocket,
  mdiTram,
  mdiWalk,
  mdiVanPassenger,
  mdiVanUtility,
  mdiTaxi,
  mdiPalmTree,
} from "@mdi/js";
import Icon from "@mdi/react";
import {
  mdiBasket,
  mdiFood,
  mdiCoffee,
  mdiHome,
  mdiCar,
  mdiTrain,
  mdiAirplane,
  mdiShopping,
  mdiGift,
  mdiHeart,
  mdiDumbbell,
  mdiMovie,
  mdiSchool,
  mdiBriefcase,
  mdiCash,
  mdiBank,
  mdiCellphone,
  mdiPaw,
  mdiTag,
  mdiLightbulb,
  mdiMedicalBag,
  mdiSilverwareForkKnife,
  mdiGasStation,
  mdiCart,
  mdiWallet,
  mdiCurrencyGbp,
  mdiCreditCard,
  mdiTshirtCrew,
} from "@mdi/js";
import type { Category } from "./types";
const icons: Record<string, [string, string]> = {
  "mdi-bank-transfer": ["Bank transfer", mdiBankTransfer],
  "mdi-bank-transfer-in": ["Bank transfer in", mdiBankTransferIn],
  "mdi-bank-transfer-out": ["Bank transfer out", mdiBankTransferOut],
  "mdi-account-cash": ["Account cash", mdiAccountCash],
  "mdi-chart-areaspline": ["Chart areaspline", mdiChartAreaspline],
  "mdi-finance": ["Finance", mdiFinance],
  "mdi-piggy-bank": ["Piggy bank", mdiPiggyBank],
  "mdi-safe": ["Safe", mdiSafe],
  "mdi-send": ["Send", mdiSend],
  "mdi-currency-eur": ["Currency eur", mdiCurrencyEur],
  "mdi-currency-usd": ["Currency usd", mdiCurrencyUsd],
  "mdi-bitcoin": ["Bitcoin", mdiBitcoin],
  "mdi-camera": ["Camera", mdiCamera],
  "mdi-guitar-acoustic": ["Guitar acoustic", mdiGuitarAcoustic],
  "mdi-headphones": ["Headphones", mdiHeadphones],
  "mdi-microphone": ["Microphone", mdiMicrophone],
  "mdi-monitor": ["Monitor", mdiMonitor],
  "mdi-music": ["Music", mdiMusic],
  "mdi-piano": ["Piano", mdiPiano],
  "mdi-tablet": ["Tablet", mdiTablet],
  "mdi-television": ["Television", mdiTelevision],
  "mdi-controller": ["Controller", mdiController],
  "mdi-watch": ["Watch", mdiWatch],
  "mdi-drama-masks": ["Drama masks", mdiDramaMasks],
  "mdi-beer": ["Beer", mdiBeer],
  "mdi-bottle-soda": ["Bottle soda", mdiBottleSoda],
  "mdi-bowl-mix": ["Bowl mix", mdiBowlMix],
  "mdi-cookie": ["Cookie", mdiCookie],
  "mdi-cup": ["Cup", mdiCup],
  "mdi-cupcake": ["Cupcake", mdiCupcake],
  "mdi-fish": ["Fish", mdiFish],
  "mdi-food-fork-drink": ["Food fork drink", mdiFoodForkDrink],
  "mdi-glass-cocktail": ["Glass cocktail", mdiGlassCocktail],
  "mdi-grill": ["Grill", mdiGrill],
  "mdi-silverware": ["Silverware", mdiSilverware],
  "mdi-hamburger": ["Hamburger", mdiHamburger],
  "mdi-pizza": ["Pizza", mdiPizza],
  "mdi-bed-double": ["Bed double", mdiBedDouble],
  "mdi-cake": ["Cake", mdiCake],
  "mdi-coffin": ["Coffin", mdiCoffin],
  "mdi-firework": ["Firework", mdiFirework],
  "mdi-food-turkey": ["Food turkey", mdiFoodTurkey],
  "mdi-halloween": ["Halloween", mdiHalloween],
  "mdi-party-popper": ["Party popper", mdiPartyPopper],
  "mdi-pine-tree": ["Pine tree", mdiPineTree],
  "mdi-snowflake": ["Snowflake", mdiSnowflake],
  "mdi-antenna": ["Antenna", mdiAntenna],
  "mdi-water": ["Water", mdiWater],
  "mdi-flash": ["Flash", mdiFlash],
  "mdi-fire": ["Fire", mdiFire],
  "mdi-umbrella": ["Umbrella", mdiUmbrella],
  "mdi-water-pump": ["Water pump", mdiWaterPump],
  "mdi-web": ["Web", mdiWeb],
  "mdi-wifi": ["Wifi", mdiWifi],
  "mdi-baby-carriage": ["Baby carriage", mdiBabyCarriage],
  "mdi-shield-car": ["Shield car", mdiShieldCar],
  "mdi-garage": ["Garage", mdiGarage],
  "mdi-cog": ["Cog", mdiCog],
  "mdi-wrench": ["Wrench", mdiWrench],
  "mdi-hammer": ["Hammer", mdiHammer],
  "mdi-gauge": ["Gauge", mdiGauge],
  "mdi-hanger": ["Hanger", mdiHanger],
  "mdi-cash-register": ["Cash register", mdiCashRegister],
  "mdi-store": ["Store", mdiStore],
  "mdi-wallet-giftcard": ["Wallet giftcard", mdiWalletGiftcard],
  "mdi-pill": ["Pill", mdiPill],
  "mdi-basketball": ["Basketball", mdiBasketball],
  "mdi-bike": ["Bike", mdiBike],
  "mdi-bowling": ["Bowling", mdiBowling],
  "mdi-run": ["Run", mdiRun],
  "mdi-soccer": ["Soccer", mdiSoccer],
  "mdi-tennis": ["Tennis", mdiTennis],
  "mdi-trophy": ["Trophy", mdiTrophy],
  "mdi-yoga": ["Yoga", mdiYoga],
  "mdi-ticket": ["Ticket", mdiTicket],
  "mdi-ambulance": ["Ambulance", mdiAmbulance],
  "mdi-bag-carry-on": ["Bag carry on", mdiBagCarryOn],
  "mdi-bag-suitcase": ["Bag suitcase", mdiBagSuitcase],
  "mdi-bus": ["Bus", mdiBus],
  "mdi-rocket": ["Rocket", mdiRocket],
  "mdi-tram": ["Tram", mdiTram],
  "mdi-walk": ["Walk", mdiWalk],
  "mdi-van-passenger": ["Van passenger", mdiVanPassenger],
  "mdi-van-utility": ["Van utility", mdiVanUtility],
  "mdi-taxi": ["Taxi", mdiTaxi],
  "mdi-palm-tree": ["Palm tree", mdiPalmTree],
  "mdi-basket": ["Groceries", mdiBasket],
  "mdi-food": ["Food", mdiFood],
  "mdi-coffee": ["Coffee", mdiCoffee],
  "mdi-home": ["Home", mdiHome],
  "mdi-car": ["Car", mdiCar],
  "mdi-train": ["Transport", mdiTrain],
  "mdi-airplane": ["Travel", mdiAirplane],
  "mdi-shopping": ["Shopping", mdiShopping],
  "mdi-gift": ["Gifts", mdiGift],
  "mdi-heart": ["Health", mdiHeart],
  "mdi-dumbbell": ["Fitness", mdiDumbbell],
  "mdi-movie": ["Entertainment", mdiMovie],
  "mdi-school": ["Education", mdiSchool],
  "mdi-briefcase": ["Work", mdiBriefcase],
  "mdi-cash": ["Cash", mdiCash],
  "mdi-bank": ["Bank", mdiBank],
  "mdi-cellphone": ["Phone", mdiCellphone],
  "mdi-paw": ["Pets", mdiPaw],
  "mdi-tag": ["Other", mdiTag],
  "mdi-lightbulb": ["Utilities", mdiLightbulb],
  "mdi-medical-bag": ["Medical", mdiMedicalBag],
  "mdi-silverware-fork-knife": ["Dining", mdiSilverwareForkKnife],
  "mdi-gas-station": ["Fuel", mdiGasStation],
  "mdi-cart": ["Groceries", mdiCart],
  "mdi-wallet": ["Wallet", mdiWallet],
  "mdi-currency-gbp": ["Income", mdiCurrencyGbp],
  "mdi-credit-card": ["Payments", mdiCreditCard],
  "mdi-tshirt-crew": ["Clothing", mdiTshirtCrew],
};
export const iconOptions = Object.entries(icons).map(([value, [label]]) => ({ value, label }));
export function CategoryIcon({
  category,
  size = 44,
}: {
  category?: Pick<Category, "icon" | "color"> | null;
  size?: number;
}) {
  const key = category?.icon?.startsWith("mdi-") ? category.icon : `mdi-${category?.icon}`;
  const rawColor = category?.color ?? "";
  const expandedColor = /^#[\da-f]{3}$/i.test(rawColor)
    ? `#${rawColor
        .slice(1)
        .split("")
        .map((digit) => digit + digit)
        .join("")}`
    : rawColor;
  const color = /^#[\da-f]{6}$/i.test(expandedColor) ? expandedColor : "#64748b";
  return (
    <span
      className="flex shrink-0 items-center justify-center rounded-full"
      style={{ width: size, height: size, backgroundColor: `${color}22` }}
      aria-hidden="true"
    >
      <Icon path={icons[key]?.[1] ?? mdiTag} size={0.95} color={color} />
    </span>
  );
}
